Repository FEMessage/upload-to-ali, pull requests merged in 2019-11, with the labels that each got.

#106 fix: 图片列表宽度小于容器时没有折行的bug
  .eslintrc.js
  package.json
  src/components/draggable-list.vue
  src/upload-to-ali.vue
  yarn.lock
Labels: bug

#114 feat: 允许用户自定义处理文件大小超出size限制的逻辑
  docs/on-oversize.md
  src/upload-to-ali.vue
Labels: enhancement

#115 refactor: upload函数
  src/upload-to-ali.vue
Labels: refactor

#117 docs: 切换图床
  README-zh.md
  README.md
  docs/guide-ali-oss.md
Labels: documentation
