Repository FEMessage/upload-to-ali, pull requests merged in 2019-07, with the labels that each got.

#47 docs: add english readme
  README-en.md
Labels: enhancement

#49 fix: 删除文件时报错
  src/upload-to-ali.vue
Labels: bug

#48 fix: 多次上传同一张不符合的文件，只有第一次有提示
  src/upload-to-ali.vue
Labels: bug

#61 docs: 增加Guide章节
  docs/guide-ali-oss.md
  styleguide.config.js
Labels: documentation

#68 fix: 处理文件名中的非法字符
  src/upload-to-ali.vue
Labels: bug

#71 chore(babel): 删除 absoluteRuntime 设置项
  .babelrc.js
Labels: chore

#69 feat: 上传非图片文件不需要写slot
  docs/file.md
  src/components/upload-item.vue
  src/upload-to-ali.vue
Labels: enhancement

#74 fix: 修复样式问题
  package.json
  src/components/draggable-list.vue
  src/components/upload-item.vue
  src/upload-to-ali.vue
  test/file-name.test.js
Labels: bug

#75 docs: README弃用本地assets使用在线图片
  README.md
Labels: documentation

#76 test: 抽离切分文件名方法，修改相关单测
  src/components/upload-item.vue
  src/upload-to-ali.vue
  src/utils.js
  test/file-name.test.js
  test/index.test.js
  test/sum.js
  test/utils.test.js
Labels: test

#79 docs: update README badges & contributing
  .github/badge.yml
  .grenrc.js
  .stylelintrc
  .travis.yml
  README-en.md
  README.md
  notify.sh
  package.json
Labels: documentation
