Repository FEMessage/upload-to-ali, pull requests merged in 2019-12, with the labels that each got.

#119 feat!: 可以通过action直接请求上传接口，并移除key与secret的注入
  .eslintrc.js
  docs/request.md
  package.json
  src/upload-to-ali.vue
  src/utils.js
  styleguide.config.js
  test/utils.test.js
  yarn.lock
Labels: breaking-change

#128 fix: eslint-plugin-jest 应该是 devDependencies
  package.json
  yarn.lock
Labels: bug

#130 feat: 添加全局注册 request 功能
  docs/guide-global-register.md
  src/index.js
  src/upload-to-ali.vue
  src/utils.js
Labels: enhancement

#133 fix: catch compressor 报的错
  src/upload-to-ali.vue
Labels: bug

#137 chore(deps): upgrade gren
  .grenrc.js
  package.json
  yarn.lock
Labels: dependencies

#138 fix: default slot not working
  docs/slot-default.md
  src/upload-to-ali.vue
  yarn.lock
Labels: bug
